### ISSUE TITLE
Finish "How To" guide

### ISSUE THREAD

**Issue by arirawr** [EmbarkStudios/opensource#2]
Finish the sections outlined in the how-to guide.

- [x] Issues and pull requests
- [x] Maintainer responsibilities
- [x] Communications/Discord info

**Comment by repi** [comment]
Also need to move over our more concrete how to for Rust projects here and updated them. https://github.com/EmbarkStudios/rust-ecosystem/blob/main/open-sourcing.md

**Comment by repi** [comment]
Also need to update the how-to guide steps to include:
- updating embark.dev
- updating embark.rs
- announcing on Discord (and maybe other channels like r/rust)

Don't think this is documented anywhere which @davidpdrsn ran into now with releasing `tryhard`

**Comment by repi** [comment]
Another thing, all of our open source repos should have the [EmbarkStudios / Open Source Admins](https://github.com/orgs/EmbarkStudios/teams/open-source-admins) added as admin to them also, this can be done at any time by an admin but nicest if the author makes sure to do this from get go so can be in the instructions as well

![image](https://user-images.githubusercontent.com/1262692/100158290-39912c00-2eac-11eb-9ebb-639f06da0c30.png)


Example from cargo-deny:

https://github.com/EmbarkStudios/cargo-deny/settings/access
![image](https://user-images.githubusercontent.com/1262692/100158396-66ddda00-2eac-11eb-8877-14fa15f833e7.png)

**Comment by lpil** [comment]
Maintenance guide is in: https://github.com/EmbarkStudios/opensource/blob/main/content/maintenance-guidelines.md

Anything else we would like to include here?

**Comment by arirawr** [comment]
I think this is done 🚢
