### ISSUE TITLE
Ensure public repos conform to our standards

### ISSUE THREAD

**Issue by lpil** [EmbarkStudios/opensource#31]
Recently we had a repo published while not yet conforming to our open source standards. This can happen because the author was unaware of our guidelines, or because by accident.

We want to ensure that this doesn't happen, and we don't want the discovery of any issues to be a manual process.

## Actions

- [ ]  We want people to be aware of our guidelines so they can follow them. Is there something we can do to improve awareness?
- [ ] We may want to restrict creation of public repos so that only an admin can do this, during which they verify that the repo conforms. This is not extra work as an admin is already needed for adding the appropriate user groups to the repo. Forks must still be permitted.
- [x] We may want to add some form of alerting around repos that do not conform. We currently do this for the repos in the website's data.json, but other repos are not checked. We may want to extend this to include all public non-fork non-archived repos.

**Comment by lpil** [comment]
This check was a good one to add, found a few problem ones:

```
✔️ nfd2 (Jake-Shadle)
✔️ blender-tools (moppius)
❌ .github
    Unable to determine maintainers
    Caused by:
        0: Unable to download EmbarkStudios/.github:.github/CODEOWNERS
        1: File not found in repo
        2: Expected status code 200, got 404

    Project not included in opensource-website data.json

✔️ opensource-website (arirawr, lpil)
✔️ gke-accelerated-xorg-example (lpil)
❌ opensource-template
    No maintainers were found for * the CODEOWNERS file

    Project not included in opensource-website data.json

❌ rust-ecosystem
    Project not included in opensource-website data.json

✔️ helix-oidc (0ax1)
❌ relnotes
    Unable to determine maintainers
    Caused by:
        0: Unable to download EmbarkStudios/relnotes:.github/CODEOWNERS
        1: File not found in repo
        2: Expected status code 200, got 404

    Project not included in opensource-website data.json

❌ opensource
    Unable to determine maintainers
    Caused by:
        0: Unable to download EmbarkStudios/opensource:.github/CODEOWNERS
        1: File not found in repo
        2: Expected status code 200, got 404

    Project not included in opensource-website data.json

✔️ puffin (emilk)
✔️ tame-gcs (Jake-Shadle)
✔️ physx-rs (tgolsson, hrydgard)
✔️ spirv-tools-rs (Jake-Shadle)
✔️ cargo-deny-action (Jake-Shadle)
❌ octobors
    No maintainers were found for * the CODEOWNERS file

    Project not included in opensource-website data.json

✔️ cargo-deny (Jake-Shadle)
✔️ ash-molten (MaikKlein, repi)
✔️ review-action (Jake-Shadle)
❌ skyhook
    Project not included in opensource-website data.json

✔️ cfg-expr (Jake-Shadle)
✔️ buildkite-jobify (Jake-Shadle)
✔️ texture-synthesis (Jake-Shadle, anopara, h3r2tic)
✔️ superluminal-perf-rs (repi)
✔️ krates (Jake-Shadle)
✔️ tame-oauth (Jake-Shadle)
✔️ spdx (Jake-Shadle)
✔️ cargo-fetcher (Jake-Shadle)
❌ sentry-contrib-rust
    Unable to determine maintainers
    Caused by:
        0: Unable to download EmbarkStudios/sentry-contrib-rust:.github/CODEOWNERS      
        1: File not found in repo
        2: Expected status code 200, got 404

    Project not included in opensource-website data.json

✔️ rust-gpu (khyperia)
✔️ k8s-buildkite-plugin (iffyio)
✔️ rpmalloc-rs (repi)
✔️ tryhard (davidpdrsn)
✔️ wg-ui (suom1)
✔️ cargo-about (Jake-Shadle)
```

**Comment by lpil** [comment]
Just merged the validation script addition that checks all repos rather than just the ones listed, so if there are problem projects we will learn about them within a single working day.

I'm tempted to say that is enough for now, and we can reopen this ticket if the problem arises again. What do you think @arirawr ?

**Comment by arirawr** [comment]
One day seems like a reasonable enough timeline for me. @repi does this seem good to you?

**Comment by repi** [comment]
Sounds reasonable!
