### ISSUE TITLE
Convert all of our open source Rust repos to use our standard lints

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/opensource#35]
We now have a template for our defined standard Rust & Clippy lints that all of our Rust projects should use as default: https://github.com/EmbarkStudios/rust-ecosystem/issues/59.

We'll need to add this template to all of our existing crates, which likely also includes fixing up some code in the the different repos but many of them already have had some of these lints enabled. So let's do PRs on all of our repos to copy over the lints, think we can wait a week or so though because may soon be a v0.3 of the lints (https://github.com/EmbarkStudios/rust-ecosystem/pull/60), that we would have to copy over again. I've done a couple of the bigger ones already, and was pretty fast. 

Is a good learning Rust experience to enable lints and fix up the code, so hope multiple can take on and follow up with this.

This is a tracking issue to add the lints to all of our open source Rust projects:

- [x] [🌋 `ash-molten`](https://github.com/EmbarkStudios/ash-molten/issues/49)
- [x] [👷 `buildkite-jobify`](https://github.com/EmbarkStudios/buildkite-jobify/issues/25)
- [x] [📜 `cargo-about`](https://github.com/EmbarkStudios/cargo-about/issues/145)
- [x] [❌ `cargo-deny`](https://github.com/EmbarkStudios/cargo-deny/issues/337)
- [x] [⚙️ `cfg-expr`](https://github.com/EmbarkStudios/cfg-expr/issues/20)
- [x] [🚙 `gsutil`](https://github.com/EmbarkStudios/gsutil/issues/1) 
- [x] [📦 `krates`](https://github.com/EmbarkStudios/krates/issues/30)
- [x] [🆙 `octobors`](https://github.com/EmbarkStudios/octobors/issues/16)
- [x] [🎳 `physx`](https://github.com/EmbarkStudios/physx-rs) - https://github.com/EmbarkStudios/physx-rs/pull/128
- [x] [🐦 `puffin`](https://github.com/EmbarkStudios/puffin/issues/19)
- [x] [📓 `relnotes`](https://github.com/EmbarkStudios/relnotes/issues/3)
- [x] [🐏 `rpmalloc-rs`](https://github.com/EmbarkStudios/rpmalloc-rs/issues/17)
- [x] [🐉 `rust-gpu`](https://github.com/EmbarkStudios/rust-gpu) - https://github.com/EmbarkStudios/rust-gpu/pull/475
- [x] [🆔 `spdx`](https://github.com/EmbarkStudios/spdx/issues/34)
- [x] [🛠 `spirv-tools-rs`](https://github.com/EmbarkStudios/spirv-tools-rs/issues/16)
- [x] [🔆 `superluminal-perf`](https://github.com/EmbarkStudios/superluminal-perf-rs/issues/13)
- [x] [📂 `tame-gcs`](https://github.com/EmbarkStudios/tame-gcs/issues/45)
- [x] [🔐 `tame-oauth`](https://github.com/EmbarkStudios/tame-oauth/issues/32)
- [x] [🧬 `tame-oidc`](https://github.com/EmbarkStudios/tame-oidc/issues/8) 
- [x] [🎨 `texture-synthesis`](https://github.com/EmbarkStudios/texture-synthesis/issues/159)
- [x] [💫 `tryhard`](https://github.com/EmbarkStudios/tryhard/issues/15)

**Comment by XAMPPRocky** [comment]
I don't know if we want to do this or not, but it occur to me that we could reduce the amount the code we'd have to change each time by pulling in the `lints.rs` file at build time. This would probably the most helpful for repos that are cargo workspaces, and have a lot of different crates that need to be updated each time.

```rust
// --- In `build.rs`
type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;
const URL: &str = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/lints.rs";

fn from_network() -> Result<String> {
    Ok(reqwest::blocking::get(URL)?.text()?)
}

fn from_filesystem() -> Result<String> {
    Ok(std::fs::read_to_string("./lints.rs")?)
}

fn main() -> Result<()> {
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR")?);

    std::fs::write(out_dir.join("lints.rs"), from_network()?)?;

    Ok(())
}

// --- In `src/lib.rs`/`src/main.rs`
include!(concat!(env!("OUT_DIR"), "lints.rs"));

```

**Comment by Jake-Shadle** [comment]
I don't think we would want to do that, even though the goal is nice, downloading a file at build time that is only useful for development is unkind to users.

**Comment by repi** [comment]
Yeah no we can't do that, every lint upgrade has to be manual anyway to comply to the lints. So has to be copy'n'pasted to the crate roots and then fix the warnings that the new lints cause. But later when Cargo does have support for a separate lint file it will be easier to just copy over a file per repo at least https://github.com/EmbarkStudios/rust-ecosystem/issues/22.

**Comment by XAMPPRocky** [comment]
I've gone ahead and created an issue in all the repositories that didn't already have an open PR and tagged the issues with `help wanted` and `good first issue` in case anyone in the community wants to take them on. [Example](https://github.com/EmbarkStudios/tame-oauth/issues/32)

**Comment by repi** [comment]
@XAMPPRocky thx, and sure!

**Comment by XAMPPRocky** [comment]
All of our crates now use v0.3
