### ISSUE TITLE
Notifies me every day about build failures

### ISSUE THREAD

**Issue by lpil** [EmbarkStudios/opensource#38]
Hello! I'm getting messaged about build failures, I think because I was the last person to edit the workflow file? Unsure.

https://github.com/EmbarkStudios/opensource/actions

https://github.com/EmbarkStudios/opensource/blob/main/.github/workflows/validate-projects.yml

I can't find a way to turn off these notifications.

Could someone try making a little edit to that file and see if it sends them to them instead? Thanks

**Comment by vojd** [comment]
@lpil I think it worked. I got the notification (which I hadn't previously)

**Comment by lpil** [comment]
I don't think so! Thanks
