### ISSUE TITLE
Daily build failure spams me with notifications

### ISSUE THREAD

**Issue by lpil** [EmbarkStudios/opensource#40]
I'm getting alerted about this every day :(

Could someone make an edit to the workflow file and commit that? I think it would then shift it over to them instead.

**Comment by Jake-Shadle** [comment]
I've pushed edits to both the workflow files, let me know if you get spammed again tomorrow.

**Comment by lpil** [comment]
Thank you <3

**Comment by lpil** [comment]
Seems to have done the trick. Thanks!

**Comment by Jake-Shadle** [comment]
No worries!

**Comment by lpil** [comment]
Dang, it happened. Hmm not sure what the solution is.

**Comment by Jake-Shadle** [comment]
Darn :( Wouldn't silencing notifications for this repo work?

**Comment by Jake-Shadle** [comment]
But for now I'm just going to fix the troublesome projects so that there shouldn't be any notifications for now.

**Comment by Jake-Shadle** [comment]
Ok, I've made a change so that at least there won't be any notifications until a new project or whatnot is added.

**Comment by lpil** [comment]
> Darn :( Wouldn't silencing notifications for this repo work?

Do you know how to do this? I'm not watching it, I pressed unsubscribe in my inbox, and I had a google but didn't find anything.

I'll contact support if not.

**Comment by Jake-Shadle** [comment]
I would have figured that would be enough, but apparently it's not. :slightly_frowning_face:
