### ISSUE TITLE
Remove or archive half-started but not usuable public projects

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/opensource#8]
Went through all non-fork public repos we have (37 right) now and found a couple that are just stubs or half-started. Let's clean that up and either remove, archive or make them private. 

[Link of repos](https://github.com/embarkStudios?language=&page=1&q=&type=source) (check in incognito / not logged in to Embark)

TODO:

- [x] https://github.com/EmbarkStudios/cargo-binary  - owner: @Jake-Shadle.  this we do want, but is just a stub, make private?
- [x] https://github.com/EmbarkStudios/cargo-deny-overlay - owner: @Jake-Shadle.  remove or make private? 
- [x] https://github.com/EmbarkStudios/clearly-defined - owner: @Jake-Shadle.  remove or make private?
- [x] https://github.com/EmbarkStudios/stable-checkout-buildkite-plugin - owner: @Jake-Shadle. archive? doesn't have our template 
- [x] https://github.com/EmbarkStudios/missing-symbols - owner: @MaikKlein.  was a bug repo, archive?
- [x] https://github.com/EmbarkStudios/docker-windows - owner: @Jake-Shadle. think it is used, update to use our template 
- [x] https://github.com/EmbarkStudios/review-action - owner: @Jake-Shadle. just a stub, remove? 

cc @arirawr

**Comment by MaikKlein** [comment]
archived https://github.com/EmbarkStudios/missing-symbols

**Comment by Jake-Shadle** [comment]
Archived, updated, or made internal everything except stable-checkout. We do use it, but there is a simpler thing we can do I just can't remove it yet.

**Comment by repi** [comment]
That was fast! Thanks!

**Comment by Jake-Shadle** [comment]
Deleted the https://github.com/EmbarkStudios/stable-checkout-buildkite-plugin

**Comment by arirawr** [comment]
Great stuff - thanks for this!
Wanted to get a clean list of all our active projects and have a better way of managing them by end of year, and this helps a ton :)
